# Generated by Django 4.2.21 on 2025-05-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("science", "Естествознание"),
                            ("math", "Математика"),
                            ("quant", "Количественная характеристика"),
                            ("kazakh", "Казахский язык"),
                            ("russian", "Русский язык"),
                            ("english", "Английский язык"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("world_science", "Мир науки"),
                            ("human_earth", "Человек, Земля, Вселенная"),
                            ("materials", "Вещества и материалы"),
                            ("nature", "Живая/Неживая природа"),
                            ("energy_motion", "Энергия и движение"),
                            ("ecology", "Экология и экосистемы"),
                            ("politics", "Политическая карта"),
                        ],
                        max_length=20,
                    ),
                ),
                ("option1", models.CharField(max_length=255)),
                ("option2", models.CharField(max_length=255)),
                ("option3", models.CharField(max_length=255)),
                ("option4", models.CharField(max_length=255)),
                (
                    "correct_option",
                    models.IntegerField(
                        choices=[
                            (1, "Вариант 1"),
                            (2, "Вариант 2"),
                            (3, "Вариант 3"),
                            (4, "Вариант 4"),
                        ]
                    ),
                ),
            ],
        ),
    ]
