# Generated by Django 4.2.21 on 2025-05-21 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="Предмет")),
                ("section", models.CharField(max_length=100, verbose_name="Раздел")),
                (
                    "score",
                    models.PositiveIntegerField(
                        verbose_name="Набранное количество баллов"
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(verbose_name="Общее число вопросов"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата прохождения"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, verbose_name="Детали теста (опционально)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
