# Generated by Django 4.2.21 on 2025-05-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_testresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.IntegerField(
                choices=[
                    (1, "Вариант 1"),
                    (2, "Вариант 2"),
                    (3, "Вариант 3"),
                    (4, "Вариант 4"),
                ],
                verbose_name="Правильный вариант",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=models.CharField(max_length=255, verbose_name="Вариант 1"),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=models.CharField(max_length=255, verbose_name="Вариант 2"),
        ),
        migrations.AlterField(
            model_name="question",
            name="option3",
            field=models.CharField(max_length=255, verbose_name="Вариант 3"),
        ),
        migrations.AlterField(
            model_name="question",
            name="option4",
            field=models.CharField(max_length=255, verbose_name="Вариант 4"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(verbose_name="Вопрос"),
        ),
        migrations.AlterField(
            model_name="question",
            name="section",
            field=models.CharField(
                choices=[
                    ("world_science", "Мир науки"),
                    ("human_earth", "Человек, Земля, Вселенная"),
                    ("materials", "Вещества и материалы"),
                    ("nature", "Живая/Неживая природа"),
                    ("energy_motion", "Энергия и движение"),
                    ("ecology", "Экология и экосистемы"),
                    ("politics", "Политическая карта"),
                ],
                max_length=20,
                verbose_name="Раздел",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="subject",
            field=models.CharField(
                choices=[
                    ("science", "Естествознание"),
                    ("math", "Математика"),
                    ("quant", "Количественная характеристика"),
                    ("kazakh", "Казахский язык"),
                    ("russian", "Русский язык"),
                    ("english", "Английский язык"),
                ],
                max_length=20,
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="section",
            field=models.CharField(
                choices=[
                    ("world_science", "Мир науки"),
                    ("human_earth", "Человек, Земля, Вселенная"),
                    ("materials", "Вещества и материалы"),
                    ("nature", "Живая/Неживая природа"),
                    ("energy_motion", "Энергия и движение"),
                    ("ecology", "Экология и экосистемы"),
                    ("politics", "Политическая карта"),
                ],
                max_length=100,
                verbose_name="Раздел",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="subject",
            field=models.CharField(
                choices=[
                    ("science", "Естествознание"),
                    ("math", "Математика"),
                    ("quant", "Количественная характеристика"),
                    ("kazakh", "Казахский язык"),
                    ("russian", "Русский язык"),
                    ("english", "Английский язык"),
                ],
                max_length=100,
                verbose_name="Предмет",
            ),
        ),
    ]
