# Generated by Django 4.2.21 on 2025-05-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0005_trainingtestresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="section",
            field=models.CharField(
                choices=[
                    ("world_science", "Мир науки"),
                    ("human_earth", "Человек, Земля, Вселенная"),
                    ("materials", "Вещества и материалы"),
                    ("nature", "Живая/Неживая природа"),
                    ("energy_motion", "Энергия и движение"),
                    ("ecology", "Экология и экосистемы"),
                    ("politics", "Политическая карта"),
                ],
                max_length=30,
                verbose_name="Раздел",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="subject",
            field=models.CharField(
                choices=[
                    ("science", "Естествознание"),
                    ("math", "Математика"),
                    ("logic", "Логика и количественные характеристики"),
                    ("Kazakh", "Казахский язык"),
                    ("Russian", "Русский язык"),
                    ("English", "Английский язык"),
                ],
                max_length=30,
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="subject",
            field=models.CharField(
                choices=[
                    ("science", "Естествознание"),
                    ("math", "Математика"),
                    ("logic", "Логика и количественные характеристики"),
                    ("Kazakh", "Казахский язык"),
                    ("Russian", "Русский язык"),
                    ("English", "Английский язык"),
                ],
                max_length=100,
                verbose_name="Предмет",
            ),
        ),
    ]
